name: React application DevSecOps workflow
on: [push]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: action/checkout@v2
      - name: NPM install
        run: npm install
      - name: Start npm
        run: npm start
      - name: Build npm
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Surge install
        run: npm install -g surge
      - name: run Surge
        run: surge build/