name: React application DevSecOps workflow
on: [push]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2

      - name: NPM install
        run: npm install

      - name: Start npm
        run: npm start

      - name: Build npm
        run: npm run build

      - name: upload the build
        run: actions/upload-artifact@v2
        with:
          name: Build file
          path: build/




  test:
    runs-on: ubuntu-latest
    steps:
      - name: NPM test
        run: npm test


  deploy:
    runs-on: ubuntu-latest
    needs: [build,test]
    steps:
      - name: Surge install
        run: npm install -g surge
      - name: download the build file
        run: actions/download-artifcats@v2
        with:
          name:Build file
      - name: run Surge
        run: surge build/