name: React application DevSecOps workflow
on: [push]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2

      - name: NPM install
        run: npm install

      - name: Build npm
        run: npm run build

      - name: upload the build
        uses: actions/upload-artifact@v2
        with:
          name: Build file
          path: build




  test:
    runs-on: ubuntu-latest
    steps:
      - name: NPM test
        run: npm test
        continue-on-error: true


  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:

      - name: Clone the repository
        uses: actions/checkout@v2
      - name: Surge install
        run: npm install -g surge
      - name: download the build file
        uses: actions/download-artifcats@v2
        with:
          name: Build file
          if: always()
      - name: Debugging verify the path
        run: ls -R
      - name: run Surge
        run: surge ./ ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}